package ex25.Base;

public enum PasswordFlags {
    CONTAINS_FEWER_THAN_EIGHT_CHARACTERS,
    CONTAINS_AT_LEAST_EIGHT_CHARACTERS,
    CONTAINS_ONLY_LETTERS,
    CONTAINS_AT_LEAST_ONE_LETTER,
    CONTAINS_ONLY_NUMBERS,
    CONTAINS_AT_LEAST_ONE_NUMBER,
    CONTAINS_AT_LEAST_SPECIAL_CHARACTER,
    CONTAINS_ONLY_SPECIAL_CHARACTERS
}
